# netlify.toml - Alternative configuration method
# Place this file in your project root (same level as package.json)

[build]
  # Build command (adjust if needed)
  command = "npm run build"
  # Directory to publish (adjust if needed)
  publish = "dist"

# SPA redirect rule - serves index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Force HTTPS
[[redirects]]
  from = "http://wordsmithscorner.netlify.app/*"
  to = "https://wordsmithscorner.netlify.app/:splat"
  status = 301
  force = true

# Optional: Add custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"